config/routes.rb
BankApp::Application.routes.draw do
  get "users/new"

  resources :users
  resources :accounts
  resources :sessions, only: [:new, :create, :destroy]

  root 'static_pages#home'
  match '/contact',      to: 'static_pages#contact',  via: 'get'

  match '/signup',       to: 'users#new',             via: 'get'
  match '/index',        to: 'users#index',           via: 'get'

  match '/signin',       to: 'sessions#new',          via: 'get'
  match '/signout',      to: 'sessions#destroy',      via: 'delete'

  match '/transfer',     to: 'accounts#transfer',     via: 'post'
  match '/deposit',      to: 'accounts#deposit',      via: 'post'
  match '/withdraw',     to: 'accounts#withdraw',     via: 'post'

  get 'accounts/:id/:type' => 'accounts#edit', as: :modify
  get 'user/:id/' => 'users#manage', as: :manage












end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :accounts, dependent: :destroy

	has_secure_password

	before_save { email.downcase }
	before_create :create_remember_token

	validates	:name, presence: true, length: { maximum: 50 }

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
	validates	:email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

	validates	:password, length: { minimum: 6 }

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.encrypt(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private
	def create_remember_token
		self.remember_token = User.encrypt(User.new_remember_token)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action	:admin_user,		only: [:destroy, :create, :new, :index]
	before_action	:correct_user,		only: [:edit, :update, :show]


	def new
		@user = User.new
	end

	def show
		if (current_user.admin?)
			@user = User.find(params[:id].to_i)
			@accounts = @user.accounts.all
		else
			@user = current_user
			@accounts = @user.accounts.all
		end
	end

	def manage
		@user = User.find(params[:id].to_i)
		redirect_to user_path(@user)
	rescue
		flash[:error] = "Problem finding user"
		redirect_to root_url
	end

	def edit
	end

	def update
		if @user.update_attributes(user_params)
			flash[:success] = "Profile updated"
			if @user.admin?
				redirect_to index_path
				return
			else
				redirect_to @user
				return
			end
		else
			render 'edit'
		end
	end

	def index
		@users = User.paginate(page: params[:page])
	end

	def create
		@user = User.new(user_params)
		if @user.save
			@account = @user.accounts.build(balance: 0.0, name: "Savings")
			if @account.save
				flash.now[:success] = "User created"
				redirect_to user_path(@user)
				return
			else
				flash.now[:error] = "User created but could not create default account"
				redirect_to user_path(@user)
			end
		else
			render 'new'
		end
	end

	def destroy
		fndUser = User.find(params[:id])
		unless fndUser == current_user
			fndUser.destroy
			flash[:success] = "User deleted"
			redirect_to index_path
		else
			flash[:error] = "Cannot delete self."
			redirect_to root_url
		end
	end

	private
	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end

	def correct_user
		@user = User.find(params[:id])
		redirect_to(root_url) unless (current_user?(@user) || current_user.admin?)
	rescue
		redirect_to(root_url)
	end

	def admin_user
		redirect_to(root_url) unless current_user.admin?
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<% if !user.admin? %>
<li>
	
	<%= user.name  %> | <%= link_to "Manage Accounts", manage_path(id: user.id) %> | <%= link_to "Delete", user, method: :delete, data: { confirm: "Are you sure?" } %>
	
</li>
<% end %>

app/views/users/edit.html.erb
<div class="row">
	<div class="span4 offset3 hero-unit">
		<h2 class="center"><%= current_user.name %></h2><br>
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>

			<%= f.label :name %>
			<%= f.text_field :name %>

			<%= f.label :email %>
			<%= f.text_field :email %>

			<%= f.label :password %>
			<%= f.password_field :password %>

			<%= f.label :password_confirmation, "Confirmation" %>
			<%= f.password_field :password_confirmation %>

			<%= f.submit "Edit account", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/index.html.erb
<div class="hero-unit">
	<h2>All users</h2>

	<%= will_paginate %>
		<ul class="users">
			<%= render @users %>
		</ul>
	<%= will_paginate %>
</div>

app/views/users/new.html.erb
<div class="row">
	<div class="span4 offset3 hero-unit">
		<h1 style="font-size: 40px" class="center">Create new user</h1><br>
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>

			<%= f.label :name %>
			<%= f.text_field :name %><br>

			<%= f.label :email %>
			<%= f.text_field :email %><br>

			<%= f.label :password %>
			<%= f.password_field :password %><br>

			<%= f.label :password_confirmation, "Confirmation" %>
			<%= f.password_field :password_confirmation %><br>

			<%= f.submit "Create account", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<div class="row hero-unit">
	<% if current_user.admin? %>
		<h2 style="color: red;">You are currently logged in as an administator</h2><br>
		<h2><%= @user.name %></h2>
	<% else %>
		<h2><%= current_user.name %></h2>
	<% end %>
	<h3>Current Accounts</h3>
	<div>
		<% if @user.accounts.any? %>
			<ol class="accounts">
				<%= render @accounts %>
			</ol>
		<% else %>
			<p>You have no accounts, contact an administator to create a new one.</p>
		<% end %>
		<% if current_user.admin? %>
			<%= link_to 'Make New Account', new_account_path(@user) %>
		<% end %>
	</div>
</div>