config/routes.rb
BankApp::Application.routes.draw do
  get "users/new"

  resources :users
  resources :accounts
  resources :sessions, only: [:new, :create, :destroy]

  root 'static_pages#home'
  match '/contact',      to: 'static_pages#contact',  via: 'get'

  match '/signup',       to: 'users#new',             via: 'get'
  match '/index',        to: 'users#index',           via: 'get'

  match '/signin',       to: 'sessions#new',          via: 'get'
  match '/signout',      to: 'sessions#destroy',      via: 'delete'

  match '/transfer',     to: 'accounts#transfer',     via: 'post'
  match '/deposit',      to: 'accounts#deposit',      via: 'post'
  match '/withdraw',     to: 'accounts#withdraw',     via: 'post'

  get 'accounts/:id/:type' => 'accounts#edit', as: :modify
  get 'user/:id/' => 'users#manage', as: :manage












end

app/views/layouts/_footer.html.erb
<footer>
	<small  style="margin-left: 20px;">
		By Jacob Craig
	</small>
	<nav>
		<ul>
			<li><%= link_to "Contact", contact_path %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "Fake Bank of Southern Utah", root_path, id: "logo" %>
			<nav>
				<ul class="nav pull-right">

					<% if signed_in? %>
						<% if current_user.admin? %>
							<li><%= link_to "New User", signup_path %></li>
							<li><%= link_to "View Users", index_path %></li>
						<% else %>
							<li><%= link_to "Accounts", user_path(current_user) %></li>
						<% end %>
						<li><%= link_to "Profile", edit_user_path(current_user) %></li>
						<li><%= link_to "Sign Out", signout_path, method: 'delete' %></li>
					<% else %>
						<li><%= link_to "Home", root_path %></li>
						<li><%= link_to "Sign in", signin_path %></li>
					<% end %>

				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FBSU</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>

	<div class="container">
		<% flash.each do |key, value| %>
			<%= content_tag(:div, value, class: "alert alert-#{key}") %>
		<% end %>

		<%= yield %>

	</div>

	<%= render 'layouts/footer' %>
	<br /><br />
	<%= debug(params) if Rails.env.development? %>
</body>
</html>