config/routes.rb
BankApp::Application.routes.draw do
  get "users/new"

  resources :users
  resources :accounts
  resources :sessions, only: [:new, :create, :destroy]

  root 'static_pages#home'
  match '/contact',      to: 'static_pages#contact',  via: 'get'

  match '/signup',       to: 'users#new',             via: 'get'
  match '/index',        to: 'users#index',           via: 'get'

  match '/signin',       to: 'sessions#new',          via: 'get'
  match '/signout',      to: 'sessions#destroy',      via: 'delete'

  match '/transfer',     to: 'accounts#transfer',     via: 'post'
  match '/deposit',      to: 'accounts#deposit',      via: 'post'
  match '/withdraw',     to: 'accounts#withdraw',     via: 'post'

  get 'accounts/:id/:type' => 'accounts#edit', as: :modify
  get 'user/:id/' => 'users#manage', as: :manage












end

app/models/account.rb
class Account < ActiveRecord::Base
	belongs_to :user
	validates :name, presence: true, length: { maximum: 50 }
	validates :user_id, presence: true
	validates :balance, presence: true
	default_scope -> { order('name DESC') }
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
	require 'bigdecimal'

	before_action :correct_user, only: [:edit, :destroy]
	before_action :admin_user, only: [:new, :create]

	def new
		@account = Account.new
		@user = User.find_by(id: params[:format])
	end

	def create
		@user = User.find_by(id: params[:user])
		@account = @user.accounts.build(balance: 0.0, name: account_params[:name])
		if @account.save
			flash[:success] = "New account created."
			redirect_to user_path(@user)
		else
			flash[:error] = "Could not create account."
			redirect_to user_path(@user)
		end
	end

	def edit
		@user = current_user
		@account = current_user.accounts.find(params[:id])
	rescue
		flash[:error] = "There was a problem. Please contact an administator."
		redirect_to root_url
	end

	def transfer
		@account_from = current_user.accounts.find(params[:from_account].to_i)
		@account_to = current_user.accounts.find(params[:select_account][:to_account].to_i)
		amount = BigDecimal(params[:transfer_amount]).truncate(2)
		if amount <= 0.0
			flash[:error] = "Please enter a valid amount."
			redirect_to user_path(current_user)
			return
		end
		if amount > @account_from.balance
			flash[:error] = "Not enough money for request."
			redirect_to user_path(current_user)
		else
			@account_to.balance += amount
			@account_from.balance -= amount
			if @account_to.save && @account_from.save
				flash[:success] = "Transfer complete."
				redirect_to user_path(current_user)
			else
				flash[:error] = "There was a problem with the transfer. Please contact an administator."
				redirect_to root_url
			end
		end
	rescue
		flash[:error] = "There was a problem. Please contact an administator."
		redirect_to root_url
	end

	def deposit
		@account = current_user.accounts.find(params[:from_account].to_i)
		amount = BigDecimal(params[:amount]).truncate(2)
		if amount <= 0.0
			flash[:error] = "Please enter a valid amount."
			redirect_to user_path(current_user)
		else
			@account.balance += amount
			if @account.save
				flash[:success] = "Deposit complete."
				redirect_to user_path(current_user)
			else
				flash[:error] = "There was a problem with the deposit. Please contact an administator."
				redirect_to root_url
			end
		end
	rescue
		flash[:error] = "There was a problem. Please contact an administator."
		redirect_to root_url
	end

	def withdraw
		@account = current_user.accounts.find(params[:from_account].to_i)
		amount = BigDecimal(params[:amount]).truncate(2)
		if amount <= 0.0
			flash[:error] = "Please enter a valid amount."
			redirect_to user_path(current_user)
		elsif amount > @account.balance
			flash[:error] = "Not enough money for requested withdrawal"
			redirect_to user_path(current_user)
		else
			@account.balance -= amount
			if @account.save
				flash[:success] = "Withdrawal complete."
				redirect_to user_path(current_user)
			else
				flash[:error] = "There was a problem with the withdrawal. Please contact an administator."
				redirect_to root_url
			end
		end
	rescue
		flash[:error] = "There was a problem. Please contact an administator."
		redirect_to root_url
	end

	def destroy
		@account = Account.find(params[:id])
		@user = User.find_by(id: @account.user_id)
		if @account.balance == 0.0
			@account.destroy
			redirect_to user_path(@user)
		elsif @account.balance > 0.0
			flash[:error] = "You must pull out the remaining balance first."
			redirect_to user_path(@user)
		else
			flash[:error] = "Could not delete account."
		end
	end

	private
	def account_params
		params.require(:account).permit(:name)
	end

	def correct_user
		@account = current_user.accounts.find_by(id: params[:id])
		if current_user.admin?
			return
		elsif @account.nil?
			redirect_to root_url
		end
	end

	def admin_user
		redirect_to root_url unless current_user.admin?
	end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_account.html.erb
<li>
	<span class="content"><%= account.name.upcase %></span>
	<span class="balance">
		Current Balance: <%= number_to_currency(account.balance, precision: 2) %>
	</span>
	<% if (current_user?(account.user) || current_user.admin?) %>
		<% if (current_user?(account.user)) %>
			| <%= link_to 'Deposit', modify_path(id: account.id, type: 'deposit') %> | 
			<%= link_to 'Withdraw', modify_path(id: account.id, type: 'withdraw') %> | 
			<%= link_to 'Transfer', modify_path(id: account.id, type: 'transfer') %>
		<% else %>
			| <%= link_to "Delete", account, method: :delete, data: { confirm: "Are you sure?" }, title: account.name %>
		<% end %>
	<% end %>
</li>

app/views/accounts/edit.html.erb
<% if params[:type] == "transfer" %>
	<div class="row hero-unit">
		<h2><%= "#{@account.name} | #{number_to_currency(@account.balance, precision: 2)}" %></h2>
		<div>
			<% if @user.accounts.count > 1 %>
				<%= form_tag(controller: "accounts", action: "transfer", method: "patch") do %>
					<%= hidden_field_tag(:from_account, "#{@account.id}")  %>
					<%= label_tag(:transfer_amount, "Enter the amount to transfer from #{@account.name}.") %>
					<%= text_field_tag(:transfer_amount) %><br>
					<%= label_tag(:select_account, "Select the account to transfer to.") %>
					<% accounts_array_minus_current = @user.accounts.all %>
					<% accounts_array_minus_current.delete(@account) %>
					<%= collection_select(:select_account, :to_account, accounts_array_minus_current, :id, :name) %> <br>
					<%= submit_tag("Transfer", class: "btn btn-primary") %>
				<% end %>
			<% else %>
				<p>You have no accounts to transfer to, create another one to continue</p><br>
				<%= link_to "Go Back", user_path(@account.user_id), class: "btn btn-primary" %>
			<% end %>
		</div>
	</div>
<% elsif params[:type] == "deposit" %>
	<div class="row hero-unit">
		<h2><%= "#{@account.name} | #{number_to_currency(@account.balance, precision: 2)}" %></h2>
		<div>
			<%= form_tag(controller: "accounts", action: "deposit", method: "patch") do %>
				<%= hidden_field_tag(:from_account, "#{@account.id}")  %>
				<%= label_tag(:amount, "Enter amount to deposit.") %>
				<%= text_field_tag :amount %><br>
				<%= submit_tag "Deposit", class: "btn btn-primary" %>
			<% end %>
		</div>
	</div>
<% elsif params[:type] == "withdraw" %>
		<h2><%= "#{@account.name} | #{number_to_currency(@account.balance, precision: 2)}" %></h2>
		<div>
			<%= form_tag(controller: "accounts", action: "withdraw", method: "patch") do %>
				<%= hidden_field_tag(:from_account, "#{@account.id}")  %>
				<%= label_tag(:amount, "Enter amount to withdraw.") %>
				<%= text_field_tag :amount %><br>
				<%= submit_tag "Withdraw", class: "btn btn-primary" %>
			<% end %>
		</div>
	</div>
<% else %>
	<% flash.now[:error] = "There was a problem with your request" %>
	<center><%= link_to "Home", root_url, class: "btn btn-large btn-primary center" %></center>
<% end %>

app/views/accounts/new.html.erb
<%= form_for(@account) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>

	<%= hidden_field_tag(:user, @user.id) %>
	
	<%= f.label :name, "New Account Name" %>
	<%= f.text_field :name %>
	<br>

	<%= f.submit "Create", class: "btn btn-primary" %>
<% end %>